DROP TABLE IF EXISTS DEPARTMENTS;

CREATE TABLE  DEPARTMENT (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fName VARCHAR(250) NOT NULL,
    lName VARCHAR(250) NOT NULL,
    email VARCHAR(250) DEFAULT NULL,
);